### PR TITLE
feat: added working dark-mode button

### LINKED ISSUE #7: Add dark mode to website
Please assign this issue to me. I've worked on it locally.

### PR DESCRIPTION
**Pull request by SujayShanbhag**
Fixes #7 
This PR adds a dark mode button to the website. The button uses virtual classes to change theme.
NOTE: Please add "hactoberfest-accepted" label to this PR.🙏🏻🙏🏻

### CODE REVIEW

**Comment by Dnyaneshvn** [comment]
Hi Sujay,
Thanks for the PR! I've added the "hactoberfest-accepted" label.

Your PR looks great! I'm excited to see this dark mode button added to the website. I think it's going to be a great addition for users who prefer to use dark mode.
Thanks again for your contribution!

**Comment by Dnyaneshvn** [comment]
Unfortunately, I've noticed that it's not working properly.

**Comment by Dnyaneshvn** [comment]
I think it would be better to position it in the right corner

**Comment by SujayShanbhag** [comment]
> I think it would be better to position it in the right corner

Agreed @Dnyaneshvn ! I'm not very familiar with plain CSS, I tried to do it, but couldn't figure it out. So I thought, maybe someone else can fix it for you. How about I open a issue for the same?

**Comment by Dnyaneshvn** [comment]
Ok, you can create an issue for that.

**Pull request merged**
